import fs from "fs";
import path from "path";
import { config } from "./config";
import { log } from "./logger";

// First line of every file we generate. Its presence is how we know a .env is OURS to
// overwrite - a hand-made .env without it is never touched.
const HEADER =
  '# Generated by Virtual Employee from projects.json ("env"). Do not edit - it is rewritten on every start/task.';

/** Quotes a value for .env syntax when it contains characters that would break parsing. */
function formatValue(value: string): string {
  if (/[\s#"'`$\\]/.test(value)) {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return value;
}

/**
 * Writes each project's "env" vars into a real `.env` file inside every member repo folder,
 * so tools Claude runs there (migrations, seeds, dev servers) find the file like on a normal
 * dev machine. Also marks `.env` in the repo's local git exclude so it can never be committed.
 * Idempotent and safe to call often; existing hand-made .env files are left alone.
 */
export function materializeEnvFiles(): void {
  for (const project of config.projects) {
    const vars = project.env;
    if (!vars || Object.keys(vars).length === 0) continue;

    for (const repo of project.repos) {
      const repoDir = repo.subdir === "." ? project.path : path.join(project.path, repo.subdir);
      try {
        if (!fs.existsSync(repoDir)) {
          // Repo not cloned yet (e.g. first boot before ensure-repos ran) - next call catches it.
          continue;
        }
        const envPath = path.join(repoDir, ".env");
        if (fs.existsSync(envPath) && !fs.readFileSync(envPath, "utf8").startsWith(HEADER)) {
          log("env_file_preserved_manual", { envPath });
          continue;
        }
        const body =
          HEADER +
          "\n" +
          Object.entries(vars)
            .map(([key, value]) => `${key}=${formatValue(value)}`)
            .join("\n") +
          "\n";
        fs.writeFileSync(envPath, body);
        excludeFromGit(repoDir);
        log("env_file_written", { envPath, keys: Object.keys(vars) });
      } catch (err) {
        log("env_file_failed", { repoDir, error: String(err) });
      }
    }
  }
}

/** Adds ".env" to the repo's .git/info/exclude (a local-only gitignore that never touches
 *  tracked files), so neither Claude nor a stray `git add -A` can ever commit the secrets. */
function excludeFromGit(repoDir: string): void {
  try {
    if (!fs.existsSync(path.join(repoDir, ".git"))) return;
    const excludePath = path.join(repoDir, ".git", "info", "exclude");
    fs.mkdirSync(path.dirname(excludePath), { recursive: true });
    const existing = fs.existsSync(excludePath) ? fs.readFileSync(excludePath, "utf8") : "";
    if (!existing.split(/\r?\n/).includes(".env")) {
      fs.appendFileSync(excludePath, (existing && !existing.endsWith("\n") ? "\n" : "") + ".env\n");
    }
  } catch (err) {
    log("env_git_exclude_failed", { repoDir, error: String(err) });
  }
}
